### ISSUE TITLE
Error: Invariant failed

### ISSUE THREAD

**Issue by konotorii** [remix-run/blues-stack#137]
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

1. Run `npx create-remix@latest --template remix-run/blues-stack test`
2. Run `npm run build`
3. Run `npm start`

### Expected Behavior

Roughly the same thing that happens when running ```npm run dev```

### Actual Behavior

met with this error

```
C:\Users\Konotorii\Documents\CoDiNg\React\test\node_modules\tiny-invariant\dist\tiny-invariant.cjs.js:10
        throw new Error(prefix);
              ^
Error: Invariant failed
    at invariant (C:\Users\Konotorii\Documents\CoDiNg\React\test\node_modules\tiny-invariant\dist\tiny-invariant.cjs.js:10:15)
    at getClient (C:\Users\Konotorii\Documents\CoDiNg\React\test\build\index.js:88:37)
    at Object.<anonymous> (C:\Users\Konotorii\Documents\CoDiNg\React\test\build\index.js:85:10)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Konotorii\Documents\CoDiNg\React\test\build\server.js:45266:78)
```

running latest version

**Comment by konotorii** [comment]
it appears i did not.... and that fixed it
