### ISSUE TITLE
Install an esm package dependency

### ISSUE THREAD

**Issue by github-mathieu-salles** [remix-run/blues-stack#231]
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

- Create a project using this template
- Try to install an esm package (I used [mine](https://www.npmjs.com/package/@argia/freddie) but also [this one](https://www.npmjs.com/package/favicon-marquee) to be sure)

### Expected Behavior

Being able to use an esm package to my project

### Actual Behavior

I'm getting this error 

` error /Users/.../node_modules/cypress: Command failed.
Exit code: 1
Command: node index.js --exec install
Arguments: 
Directory: /Users/.../node_modules/cypress
Output:
/Users/.../node_modules/cli-truncate/index.js:3
const stringWidth = require('string-width');`
`                    ^`

`Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/.../node_modules/string-width/index.js from /Users/.../node_modules/cli-truncate/index.js not supported.
Instead change the require of /Users/.../node_modules/string-width/index.js in /Users/.../node_modules/cli-truncate/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/.../node_modules/cli-truncate/index.js:3:21)
    at Object.<anonymous> (/Users/.../node_modules/listr2/dist/renderer/default.renderer.js:4:21) {
  code: 'ERR_REQUIRE_ESM'`

I tried to make the modification from this [PR](https://github.com/remix-run/blues-stack/pull/206/files) but without success. I might forget something 🤔 
I can install these packages without problem to a project using remix without the template if it helps

**Comment by 1willcobb** [comment]
I am also having tons of esm issues with @mdx-js/mdx. Cant get it to run.

**Comment by MichaelDeBoey** [comment]
These will probably be solved once #206 is merged
